# TF-305/1-workspaces Test: workspace-driven configuration
# No input variables (uses terraform.workspace built-in)
# Provider: hashicorp/local (no credentials required)
# Run: terraform test (from the example/ directory)
#
# Teaching focus: terraform.workspace drives different config per environment.
# Note: terraform test always runs in the "default" workspace.
# The test validates the default workspace behavior (size=small, replicas=1).

run "creates_workspace_config_for_default_workspace" {
  command = apply

  assert {
    condition     = endswith(local_file.workspace_config.filename, "default.conf")
    error_message = "In the default workspace, config file should be named 'default.conf'"
  }

  assert {
    condition     = strcontains(local_file.workspace_config.content, "environment = default")
    error_message = "Config should show workspace name 'default'"
  }

  assert {
    condition     = strcontains(local_file.workspace_config.content, "size        = small")
    error_message = "Default workspace should use size=small"
  }

  assert {
    condition     = strcontains(local_file.workspace_config.content, "replicas    = 1")
    error_message = "Default workspace should use replicas=1"
  }
}

run "config_file_contains_terraform_comment" {
  command = apply

  assert {
    condition     = strcontains(local_file.workspace_config.content, "# Generated by Terraform")
    error_message = "Config file should contain the generated-by comment"
  }

  assert {
    condition     = strcontains(local_file.workspace_config.content, "# Configuration for workspace: default")
    error_message = "Config file should identify the workspace in the header comment"
  }
}