# TF-301 Supplement: sensitive Variables, Outputs & nonsensitive()
# Demonstrates how sensitive values are redacted in plan/apply output

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Using sensitive variables in resources
#
# When you run 'terraform plan', the content will show as:
#   + content = (sensitive value)
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "app_config" {
  # This content is automatically sensitive because it contains var.db_password
  content = <<-EOT
    # Application Configuration
    # Generated by Terraform — DO NOT COMMIT THIS FILE
    app_name    = "${var.app_name}"
    db_host     = "${var.db_host}"
    db_password = "${var.db_password}"
    api_key     = "${var.api_key}"
  EOT
  filename = "${path.module}/app.conf"
}

# ─────────────────────────────────────────────────────────────────────────────
# Non-sensitive resource — shows normally in plan output
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "public_config" {
  content  = "app_name = ${var.app_name}\ndb_host = ${var.db_host}"
  filename = "${path.module}/public.conf"
}