# TF-303: Terraform Test Framework — Example Module
#
# This module manages a set of application configuration files.
# It demonstrates patterns that are easy to test:
#   - Variables with validation
#   - Conditional resources (count)
#   - for_each resource creation
#   - Computed locals
#   - Multiple outputs
#
# Uses the `local` provider so tests run anywhere (no libvirt daemon needed).
# The README shows equivalent libvirt examples for real infrastructure.

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Locals — computed values that tests can assert against
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # Normalise environment name to lowercase
  environment = lower(var.environment)

  # Build a map of services → their config content
  service_configs = {
    for name, svc in var.services : name => {
      name    = name
      port    = svc.port
      enabled = svc.enabled
      config  = <<-EOT
        # ${name} service configuration
        # Environment: ${local.environment}
        # Generated by Terraform — do not edit manually
        service_name = "${name}"
        port         = ${svc.port}
        enabled      = ${svc.enabled}
        log_level    = "${var.log_level}"
      EOT
    }
  }

  # Only enabled services
  enabled_services = {
    for name, svc in local.service_configs : name => svc
    if svc.enabled
  }

  # Tag map applied to all resources
  common_tags = merge(var.tags, {
    Environment = local.environment
    ManagedBy   = "terraform"
    Module      = "TF-303-test-framework"
  })
}

# ─────────────────────────────────────────────────────────────────────────────
# Config files — one per service (for_each)
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "service_config" {
  for_each = local.service_configs

  filename        = "${path.module}/output/${local.environment}/${each.key}.conf"
  content         = each.value.config
  file_permission = "0644"
}

# ─────────────────────────────────────────────────────────────────────────────
# Summary file — always created, lists all services
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "summary" {
  filename = "${path.module}/output/${local.environment}/summary.txt"
  content  = <<-EOT
    # Infrastructure Summary
    # Environment : ${local.environment}
    # Services    : ${length(var.services)}
    # Enabled     : ${length(local.enabled_services)}
    # Log Level   : ${var.log_level}
    # Tags        : ${jsonencode(local.common_tags)}
  EOT
  file_permission = "0644"
}

# ─────────────────────────────────────────────────────────────────────────────
# Debug file — only created when debug mode is enabled (conditional resource)
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "debug_info" {
  count = var.enable_debug ? 1 : 0

  filename = "${path.module}/output/${local.environment}/debug.txt"
  content  = <<-EOT
    # Debug Information
    # Environment : ${local.environment}
    # All services (including disabled):
    ${join("\n", [for name, svc in var.services : "  - ${name}: port=${svc.port} enabled=${svc.enabled}"])}
  EOT
  file_permission = "0600"
}