# TF-301 Supplement: Cross-Variable Validation (Terraform 1.9+)
# Uses the local provider — no cloud account required
#
# This example demonstrates validation conditions that reference other variables.
# All validation logic is in variables.tf.
#
# Try these to see validation in action:
#
#   FAIL (prod needs >= 3 instances):
#     terraform plan -var="environment=prod" -var="instance_count=1" -var="disk_size_gb=100"
#
#   FAIL (prod needs >= 50 GB disk):
#     terraform plan -var="environment=prod" -var="instance_count=3" -var="disk_size_gb=20"
#
#   FAIL (backups enabled but retention too low):
#     terraform plan -var="enable_backups=true" -var="backup_retention_days=3"
#
#   PASS (valid prod configuration):
#     terraform plan -var="environment=prod" -var="instance_count=3" -var="disk_size_gb=100" \
#                    -var="enable_backups=true" -var="backup_retention_days=30"
#
#   PASS (valid dev configuration — relaxed rules):
#     terraform plan -var="environment=dev" -var="instance_count=1" -var="disk_size_gb=10"

terraform {
  required_version = ">= 1.9"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Locals — derive computed values from validated inputs
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # Resource name prefix following naming convention
  name_prefix = "${var.project_name}-${var.environment}"

  # Backup summary for the config report
  backup_summary = var.enable_backups ? "Enabled (${var.backup_retention_days} days retention)" : "Disabled"

  # Compliance status — prod must have backups
  backup_compliant = var.environment != "prod" || var.enable_backups

  # Configuration report content
  config_report = <<-EOT
    # Infrastructure Configuration Report
    # Generated by Terraform — cross-variable validation example
    # Terraform 1.9+: validation conditions can reference other variables

    ## Deployment Summary
    Project:      ${var.project_name}
    Environment:  ${var.environment}
    Name Prefix:  ${local.name_prefix}

    ## Compute Configuration
    Instances:    ${var.instance_count}
    Disk Size:    ${var.disk_size_gb} GB

    ## Backup Configuration
    Backups:      ${local.backup_summary}

    ## Validation Rules Applied (Terraform 1.9+ cross-variable)
    - instance_count >= 3 when environment == "prod"  : ${var.environment == "prod" ? (var.instance_count >= 3 ? "PASS" : "FAIL") : "N/A (not prod)"}
    - disk_size_gb >= 50 when environment == "prod"   : ${var.environment == "prod" ? (var.disk_size_gb >= 50 ? "PASS" : "FAIL") : "N/A (not prod)"}
    - backup_retention >= 7 when enable_backups=true  : ${var.enable_backups ? (var.backup_retention_days >= 7 ? "PASS" : "FAIL") : "N/A (backups disabled)"}

    ## Notes
    If you see this file, all validation rules PASSED.
    Terraform would have stopped at 'plan' if any validation failed.
  EOT
}

# ─────────────────────────────────────────────────────────────────────────────
# Output the configuration report as a local file
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "config_report" {
  content  = local.config_report
  filename = "${path.module}/config-report.txt"
}