# TF-203 Supplement: jsondecode() and JSON-Driven Configuration
# Demonstrates reading JSON config files and generating JSON output

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Parse the JSON configuration file
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # jsondecode() parses the JSON file into a Terraform object
  config = jsondecode(file("${path.module}/servers.json"))

  # Filter to only enabled servers using a for expression
  enabled_servers = {
    for s in local.config.servers : s.name => s
    if s.enabled
  }

  # All servers as a map (including disabled)
  all_servers = {
    for s in local.config.servers : s.name => s
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Create config files for enabled servers only
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "server_configs" {
  for_each = local.enabled_servers

  content  = <<-EOT
    # Server: ${each.value.name}
    # Generated by Terraform from servers.json
    role = "${each.value.role}"
    port = ${each.value.port}
    env  = "${local.config.environment}"
  EOT
  filename = "${path.module}/configs/${each.key}.conf"
}

# ─────────────────────────────────────────────────────────────────────────────
# Generate a JSON deployment manifest using jsonencode()
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "deployment_manifest" {
  # jsonencode() converts a Terraform value to a JSON string
  content = jsonencode({
    generated_at    = timestamp()
    environment     = local.config.environment
    total_servers   = length(local.config.servers)
    enabled_servers = length(local.enabled_servers)
    disabled_servers = length(local.all_servers) - length(local.enabled_servers)
    server_names    = keys(local.enabled_servers)
    tags            = local.config.tags
  })
  filename = "${path.module}/deployment-manifest.json"
}