# TF-301 Section 5: Ephemeral Values (Terraform 1.10+)
#
# This example demonstrates:
# 1. Ephemeral variables — never written to state or plan files
# 2. Using ephemeral values in local-exec provisioners (allowed)
# 3. Using ephemeralasnull() to safely check if an ephemeral value was provided
# 4. The difference between sensitive and ephemeral
#
# Run with:
#   terraform init
#   terraform apply -var="db_password=MySecret123"
#   terraform apply -var="db_password=MySecret123" -var="api_token=tok-abc123"

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# LOCALS — ephemeral propagation
#
# When a local references an ephemeral variable, the local itself becomes
# ephemeral. It cannot be used in non-ephemeral outputs or resource attributes.
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # This local is ephemeral because it references var.db_password (ephemeral)
  # It can only be used in ephemeral contexts (provisioners, write-only attrs)
  connection_string = "postgresql://admin:${var.db_password}@${var.db_host}/${var.db_name}"

  # This local is NOT ephemeral — only references regular variables
  # It CAN be used in outputs and resource attributes
  db_endpoint = "${var.db_host}/${var.db_name}"

  # Use ephemeralasnull() to check if optional token was provided
  # The result is null (not the token value) — safe to store in state
  api_token_provided = ephemeralasnull(var.api_token) != null
}

# ─────────────────────────────────────────────────────────────────────────────
# RESOURCE: Public configuration file
#
# This file contains only non-sensitive, non-ephemeral values.
# It is safe to write to disk and store in state.
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "app_config" {
  filename = "${path.module}/app.conf"
  content  = <<-EOT
    # Application Configuration
    # Generated by Terraform — safe to commit (no secrets)
    app_name    = ${var.app_name}
    environment = ${var.environment}
    db_host     = ${var.db_host}
    db_name     = ${var.db_name}
    api_enabled = ${local.api_token_provided}
    # Note: db_password and api_token are NOT in this file
    # They were used ephemerally during provisioning
  EOT
}

# ─────────────────────────────────────────────────────────────────────────────
# RESOURCE: Database initialization using ephemeral password
#
# The null_resource uses a local-exec provisioner to "initialize" the database.
# The ephemeral db_password is passed to the provisioner — it is used in memory
# but NEVER written to state.
#
# In a real scenario, this would be:
#   psql -h ${var.db_host} -U admin -d ${var.db_name} -c "ALTER USER admin PASSWORD '${var.db_password}'"
# ─────────────────────────────────────────────────────────────────────────────

resource "null_resource" "db_init" {
  # Trigger re-run if the app config changes
  triggers = {
    app_name    = var.app_name
    environment = var.environment
    db_host     = var.db_host
    db_name     = var.db_name
    # NOTE: We do NOT include db_password in triggers — it's ephemeral
    # and cannot be stored in state (triggers are stored in state)
  }

  provisioner "local-exec" {
    # ✅ Ephemeral values CAN be used in provisioners
    # The password is used here but never written to state
    command = <<-EOT
      echo "Initializing database ${var.db_name} on ${var.db_host}"
      echo "Connection string would be: postgresql://admin:***@${var.db_host}/${var.db_name}"
      echo "Password length: ${length(var.db_password)} characters (not logged)"
      echo "API token provided: ${local.api_token_provided}"
    EOT
    # In production, you would use the actual password:
    # command = "psql '${local.connection_string}' -f init.sql"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# RESOURCE: Conditional API configuration
#
# Uses ephemeralasnull() to conditionally create a resource based on whether
# an ephemeral token was provided — without storing the token in state.
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "api_status" {
  filename = "${path.module}/api-status.conf"
  # local.api_token_provided is a boolean (not the token) — safe to store
  content  = "api_integration_enabled = ${local.api_token_provided}\n"
}

# ─────────────────────────────────────────────────────────────────────────────
# DEMONSTRATION: What happens with sensitive vs ephemeral
#
# Uncomment the sensitive example to compare behavior:
# ─────────────────────────────────────────────────────────────────────────────

# SENSITIVE EXAMPLE (for comparison — uncomment to test):
# variable "db_password_sensitive" {
#   type      = string
#   sensitive = true  # Redacted in output, BUT stored in state
# }
#
# resource "local_file" "sensitive_demo" {
#   filename = "${path.module}/sensitive-demo.conf"
#   content  = "password = ${var.db_password_sensitive}"
#   # After apply: check terraform.tfstate — the password IS there in plaintext!
# }
#
# EPHEMERAL EXAMPLE (current):
# After apply: check terraform.tfstate — var.db_password is NOT there at all!