# TF-302 Section 4: Write-Only Attributes (Terraform 1.11+)
#
# This example simulates the write-only attribute pattern using null_resource
# and local_file, since write-only attributes require a cloud provider that
# implements them (e.g., AWS provider 6.x for aws_db_instance.password_wo).
#
# The pattern demonstrated here is IDENTICAL to how you would use real
# write-only attributes — only the resource type differs.
#
# Real-world equivalent (requires AWS provider 6.x+):
#   resource "aws_db_instance" "main" {
#     password_wo         = var.db_password    # ephemeral, never stored
#     password_wo_version = var.db_password_version  # stored, increment to rotate
#   }
#
# Run with:
#   terraform init
#   terraform apply -var="db_password=SuperSecret123!"
#
# To simulate password rotation:
#   terraform apply -var="db_password=NewPassword456!" -var="db_password_version=2"

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# SIMULATED WRITE-ONLY PATTERN
#
# In a real provider with write-only support, the password would be passed
# directly to the resource attribute. Here we simulate it with null_resource.
#
# Key insight: the password_version IS stored in state (it's a regular number).
# The password itself is NOT stored (it's ephemeral + used only in provisioner).
# ─────────────────────────────────────────────────────────────────────────────

resource "null_resource" "database" {
  # ✅ The version IS stored in state — Terraform uses it to detect changes
  # When you increment db_password_version, Terraform re-runs the provisioner
  triggers = {
    db_name          = var.db_name
    db_host          = var.db_host
    environment      = var.environment
    password_version = var.db_password_version  # Stored — triggers rotation
    # NOTE: db_password is NOT in triggers — it's ephemeral and cannot be stored
  }

  # ✅ The password IS used here — but only in memory, never written to state
  provisioner "local-exec" {
    command = <<-EOT
      echo "=== Simulated Database Password Configuration ==="
      echo "Database: ${var.db_name} on ${var.db_host}"
      echo "Environment: ${var.environment}"
      echo "Password version: ${var.db_password_version}"
      echo "Password length: ${length(var.db_password)} chars (not logged)"
      echo "Password hash (first 4 chars): ${substr(var.db_password, 0, 4)}..."
      echo ""
      echo "In production, this would run:"
      echo "  ALTER USER admin PASSWORD '***' (password applied, not logged)"
      echo ""
      echo "State will contain: password_version=${var.db_password_version}"
      echo "State will NOT contain: the actual password"
    EOT
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# METADATA FILE — records what IS safe to store
#
# This file contains only non-secret metadata.
# The password version is stored here (not the password itself).
# ─────────────────────────────────────────────────────────────────────────────

resource "local_file" "db_metadata" {
  filename = "${path.module}/db-metadata.conf"
  content  = <<-EOT
    # Database Metadata — Generated by Terraform
    # This file is safe to inspect — no secrets here
    db_name          = ${var.db_name}
    db_host          = ${var.db_host}
    environment      = ${var.environment}
    password_version = ${var.db_password_version}
    # password: NOT STORED — ephemeral write-only value
  EOT
}

# ─────────────────────────────────────────────────────────────────────────────
# WHAT TO CHECK AFTER APPLY:
#
# 1. Look at terraform.tfstate — you will see:
#    - null_resource.database.triggers.password_version = "1"  ✅ stored
#    - null_resource.database.triggers.db_name = "appdb"       ✅ stored
#    - NO password anywhere in the state file                   ✅ not stored
#
# 2. To rotate the password:
#    terraform apply -var="db_password=NewPassword456!" -var="db_password_version=2"
#    Terraform sees password_version changed: 1 → 2, re-runs provisioner
# ─────────────────────────────────────────────────────────────────────────────