# TF-305 Section 3: Remote State Sharing — Consumer Configuration
# This is the "compute" layer that reads outputs from the networking layer.

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }

  # Compute layer stores its own state separately
  backend "local" {
    path = "../../shared-state/compute.tfstate"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Read outputs from the networking configuration via terraform_remote_state
# ─────────────────────────────────────────────────────────────────────────────
data "terraform_remote_state" "networking" {
  backend = "local"
  config = {
    path = "../../shared-state/networking.tfstate"
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Use the networking outputs to configure compute resources
# In a real setup, these would be libvirt_domain resources using the network_id
# ─────────────────────────────────────────────────────────────────────────────
resource "local_file" "vm_config" {
  content = <<-EOT
    # VM Configuration (generated by Terraform)
    # Network values sourced from networking layer via terraform_remote_state

    [network]
    network_id   = ${data.terraform_remote_state.networking.outputs.network_id}
    network_name = ${data.terraform_remote_state.networking.outputs.network_name}
    network_cidr = ${data.terraform_remote_state.networking.outputs.network_cidr}

    [compute]
    vm_name   = ${var.vm_name}
    vm_memory = ${var.vm_memory_mb}
    vm_cpus   = ${var.vm_cpus}
  EOT
  filename = "${path.module}/vm.conf"
}