# TF-305 Section 1: Terraform Workspaces
# Demonstrates terraform.workspace and workspace-driven configuration

terraform {
  required_version = ">= 1.14"
  required_providers {
    local = {
      source  = "hashicorp/local"
      version = "~> 2.7"
    }
  }
}

# ─────────────────────────────────────────────────────────────────────────────
# Workspace-driven configuration
# Run with different workspaces to see different outputs:
#   terraform workspace new dev    → creates dev.conf with size=small
#   terraform workspace new staging → creates staging.conf with size=medium
# ─────────────────────────────────────────────────────────────────────────────

locals {
  # Different resource sizes per workspace
  sizes = {
    default = "small"
    dev     = "small"
    staging = "medium"
    prod    = "large"
  }

  # Different replica counts per workspace
  replicas = {
    default = 1
    dev     = 1
    staging = 2
    prod    = 3
  }

  current_size     = lookup(local.sizes, terraform.workspace, "small")
  current_replicas = lookup(local.replicas, terraform.workspace, 1)
}

# Each workspace creates its own config file (isolated state)
resource "local_file" "workspace_config" {
  content = <<-EOT
    # Configuration for workspace: ${terraform.workspace}
    # Generated by Terraform — do not edit manually

    environment = ${terraform.workspace}
    size        = ${local.current_size}
    replicas    = ${local.current_replicas}
  EOT
  filename = "${path.module}/${terraform.workspace}.conf"
}